# Generated by Django 4.1.7 on 2023-03-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_contest_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
    ]
