# Generated by Django 4.1.7 on 2023-03-20 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_player_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='match',
            name='players',
        ),
        migrations.AddField(
            model_name='contest',
            name='teams_per_user',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='Contest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.contest'),
        ),
    ]
