# Generated by Django 4.1.7 on 2023-04-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_contest_teams_remove_match_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(related_name='players', to='game.player'),
        ),
    ]
