# Generated by Django 4.1.7 on 2023-04-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('WK', 'WK'), ('BAT', 'BAT'), ('AR', 'AR'), ('BOWL', 'BOWL')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
