# Generated by Django 4.1.7 on 2023-04-04 13:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_player_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('RH_BAT', 'Right-handed batsman'), ('LH_BAT', 'Left-handed batsman'), ('RF_FAST', 'Right-arm fast bowler'), ('LF_FAST', 'Left-arm fast bowler'), ('RF_MEDIUM_FAST', 'Right-arm medium-fast bowler'), ('LF_MEDIUM_FAST', 'Left-arm medium-fast bowler'), ('RF_MEDIUM', 'Right-arm medium bowler'), ('LF_MEDIUM', 'Left-arm medium bowler'), ('RF_OFFSPIN', 'Right-arm off-spin bowler'), ('LF_ORTHODOX', 'Left-arm orthodox spin bowler'), ('RF_LEGSPIN', 'Right-arm leg-spin bowler'), ('LF_UNORTHODOX', 'Left-arm unorthodox spin bowler'), ('RH_BAT_RF_FAST', 'Right-handed batsman and right-arm fast bowler'), ('LH_BAT_LF_FAST', 'Left-handed batsman and left-arm fast bowler'), ('RH_BAT_RF_OFFSPIN', 'Right-handed batsman and right-arm off-spin bowler'), ('LH_BAT_LF_ORTHODOX', 'Left-handed batsman and left-arm orthodox spin bowler'), ('RH_BAT_RF_LEGSPIN', 'Right-handed batsman and right-arm leg-spin bowler'), ('LH_BAT_LF_UNORTHODOX', 'Left-handed batsman and left-arm unorthodox spin bowler'), ('RH_WK', 'Right-handed wicketkeeper-batsman'), ('LH_WK', 'Left-handed wicketkeeper-batsman')], max_length=20, null=True),
        ),
    ]
