# Generated by Django 4.1.7 on 2023-04-08 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_player_player_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(max_length=25, null=True)),
                ('p2', models.CharField(max_length=25, null=True)),
                ('p1_logo', models.FileField(max_length=254, upload_to=None)),
                ('p2_logo', models.FileField(max_length=254, upload_to=None)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('UP', 'Upcoming'), ('LI', 'Live'), ('CO', 'Completed')], default='UP', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='winnings',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='match',
            name='participants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.participants'),
        ),
    ]
